fix: CI check for Velero version (#94)
Signed-off-by: Mateus Oliveira <msouzaol@redhat.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -91,3 +91,12 @@ jobs:
             echo "::error::run 'make update-non-admin-manifests' in OADP repository to update Non Admin Controller (NAC) manifests"
             exit 1
           fi
+
+      - name: Check Velero manifests
+        working-directory: ./oadp-non-admin
+        run: |
+          OADP_OPERATOR_PATH=../ make update-velero-manifests
+          if test -n "$(git status --short)"; then
+            echo "::error::run 'make update-velero-manifests' in Non Admin Controller (NAC) repository to update Velero manifests"
+            exit 1
+          fi
